name: Build and Deploy
on:
  push:
    branches: master
jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      
      - name: Install Project Dependencies
        run: npm ci
      
      - name: Install Gatsby CLI
        run: npm i -g gatsby-cli
      
      - name: Build
        run: gatsby build
      
      - name: Verify build
        run: ls -la public
      
#       - name: SSH Setup
#         uses: MrSquaare/ssh-setup-action@v1.0.0
#         with:
#           # Private key required to access the host
#           private-key: ${{ secrets.ssh_private_key }}
#           # Hostname or IP to add to the known hosts file
#           host: ${{ secrets.host }}
#           private-key-name: github
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          sudo chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.HOST }}" > ~/.ssh/known_hosts
      
      - name: SFTP upload
        run: sftp -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.HOST }} <<< $'cd ${{ secrets.DESTINATION_PATH }} \n put -r public/*'
